version: '3.7'

services:
  middleman:
    image: minusz/middleman:latest
    container_name: minusz-proxy
    build:
      context: .
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - monolith

  monolith:
    image: minusz/monolith:latest
    container_name: minusz-monolith
    expose:
      - "8000"
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5432"
volumes:
  postgres_data:
